image: openjdk:8-jdk-slim-buster

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

stages:
  - build

build:
  stage: build
  script: ./gradlew --build-cache build --stacktrace
  cache:
    key: "$CI_COMMIT_REF_NAME"
    paths:
      - build
      - .gradle
