name: Build main

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Log in to Docker Hub
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

    - name: Build with Gradle
      run: ./gradlew build

    - name: Docker tag and push
      run: |
        docker tag elm-rssfeed:latest ${{ secrets.DOCKER_USERNAME }}/elm-rssfeed
        docker push ${{ secrets.DOCKER_USERNAME }}/elm-rssfeed
