name: Build main

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the git repository
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: 21
        distribution: 'temurin'

    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

    - name: Build with Gradle
      run: ./gradlew build

    - name: Docker tag and push elm-rssfeed-convert-rss-to-json
      run: |
        docker tag elm-rssfeed-convert-rss-to-json:latest ${{ secrets.DOCKER_USERNAME }}/elm-rssfeed-convert-rss-to-json
        docker push ${{ secrets.DOCKER_USERNAME }}/elm-rssfeed-convert-rss-to-json

    - name: Docker tag and push elm-rssfeed
      run: |
        docker tag elm-rssfeed:latest ${{ secrets.DOCKER_USERNAME }}/elm-rssfeed
        docker push ${{ secrets.DOCKER_USERNAME }}/elm-rssfeed
